auth_basic/app/gig/forms.py
from flask_wtf import FlaskForm
from markupsafe import Markup
from wtforms import StringField, TextAreaField, SubmitField, DecimalField
from wtforms.validators import InputRequired, Length, NumberRange
from wtforms.widgets import Input


class PriceInput(Input):
    input_type = "number"

    def __call__(self, field, **kwargs):
        kwargs.setdefault("id", field.id)
        kwargs.setdefault("type", self.input_type)
        kwargs.setdefault("step", "0.01")
        if "value" not in kwargs:
            kwargs["value"] = field._value()
        if "required" not in kwargs and "required" in getattr(field, "flags", []):
            kwargs["required"] = True

        return Markup("""<div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    <input %s>
        </div>""" % self.html_params(name=field.name, **kwargs))


class PriceField(DecimalField):
    # NumberRangeからmin/maxへの反映については調査中。v3待ち？
    widget = PriceInput()


class GigForm(FlaskForm):
    title = StringField(
        "Title *",
        validators=[
            InputRequired("Input is required!"),
            Length(min=5, max=100,
                   message="Input must be between 5 and 100 characters long"),
        ])
    description = TextAreaField(
        "Description *",
        validators=[
            InputRequired("Input is required!"),
            Length(max=1000,
                   message="Input must be less equal to 1000 characters long"),
        ])
    payment = PriceField(
        'Payment',
        validators=[
            InputRequired("Input is required!"),
            NumberRange(min=0),
        ])
    location = StringField(
        "Location *",
        validators=[
            InputRequired("Input is required!"),
            Length(min=3, max=100,
                   message="Input must be between 3 and 100 characters long"),
        ])


class CreateGigForm(GigForm):
    submit = SubmitField("Create")


class UpdateGigForm(GigForm):
    submit = SubmitField("Update")

auth_basic/app/gig/views.py
from functools import wraps

from flask import Blueprint, render_template, flash, redirect, url_for, \
    abort, request
from werkzeug.utils import escape, unescape

from app import db
from app.auth import current_user, login_required, activation_required, role_required
from app.models import Role, Gig
from .forms import CreateGigForm, UpdateGigForm

gig = Blueprint('gig', __name__)


def gig_owner_required(f):
    @wraps(f)
    def _gig_owner_required(*args, **kwargs):
        gig = Gig.query.filter_by(slug=request.view_args.get('slug')).first()
        if not gig or not current_user.is_gig_owner(gig):
            flash('You are not the owner of that gig.', 'danger')
            return redirect(url_for('main.home'))
        return f(*args, **kwargs)

    return _gig_owner_required


@gig.route('/info/<slug>')
@login_required
@activation_required
def show(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    musicians = gig.musicians.all()
    return render_template('gig/show_gig.html', gig=gig, musicians=musicians)


@gig.route('/my_gigs')
@login_required
@activation_required
def my_gigs():
    gigs = None
    if current_user.is_role(Role.EMPLOYER):
        gigs = current_user.gigs.all()
    elif current_user.is_role(Role.MUSICIAN):
        gigs = current_user.applied_gigs.all()

    return render_template('gig/my_gigs.html', gigs=gigs)


@gig.route('/create', methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
def create():
    form = CreateGigForm()
    if form.validate_on_submit():
        gig = Gig(
            title=escape(form.title.data),
            description=escape(form.description.data),
            payment=form.payment.data,
            location=escape(form.location.data),
            employer_id=current_user.id
        )
        db.session.add(gig)
        db.session.commit()
        flash(f'The new gig has been added. "{gig.title}"', 'success')
        return redirect(url_for('gig.show', slug=gig.slug))

    return render_template('gig/create_gig.html', form=form)


@gig.route('/edit/<slug>', methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def edit(slug):
    form = UpdateGigForm()
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    if form.validate_on_submit():
        gig.update(
            title=escape(form.title.data),
            description=escape(form.description.data),
            payment=form.payment.data,
            location=escape(form.location.data)
        )
        db.session.add(gig)
        db.session.commit()
        flash('The gig has been updated.', 'success')
        return redirect(url_for('gig.show', slug=gig.slug))

    form.title.data = unescape(gig.title)
    form.description.data = unescape(gig.description)
    form.payment.data = gig.payment
    form.location.data = unescape(gig.location)
    return render_template('gig/edit_gig.html', gig=gig, form=form)


@gig.route('/delete/<slug>', methods=["POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def delete(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    db.session.delete(gig)
    db.session.commit()
    flash('The gig has been deleted.', 'success')
    return redirect(url_for('gig.my_gigs'))


@gig.route('/apply/<slug>', methods=["POST"])
@login_required
@activation_required
@role_required(Role.MUSICIAN)
def apply_to_gig(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    current_user.apply(gig)
    flash(f'You just applied to the gig: "{gig.title}".', 'success')
    return redirect(request.referrer)  # back

auth_basic/app/templates/gig/_gig.html
<div class="col col-lg-4 mb-4">
  <div class="card">
    <div class="card-body">
      <img class="card-img-top"
           src="{{ url_for('static', filename='images/gig.png') }}"
           alt="gig.png">
      <h3 class="card-title">
        <a href="{{ url_for('gig.show', slug=gig.slug) }}">{{ gig.title | safe }}</a>
      </h3>
      <h4>{{ '$%.2f' | format(gig.payment) }}</h4>
      <p>{{ gig.location | safe }}</p>
      <p class="card-text"><em>{{ gig.description | safe }}</em></p>
    </div>
    <div class="card-footer">Posted by:
      <a href="{{ url_for('account.show', username=gig.employer.username) }}">{{ gig.employer.username }}</a>
      {% if active_page == 'home' %}
        {% if current_user.is_role(Role.MUSICIAN) %}
          <br>
          {% if current_user.is_applied_to(gig) %}
            <button class="btn btn-warning" disabled>Applied...</button>
          {% else %}
            <form method="POST" action="{{ url_for('gig.apply_to_gig', slug=gig.slug) }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input type="submit" class="btn btn-warning" value="Apply">
            </form>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>

auth_basic/app/templates/gig/create_gig.html
{% extends 'base.html' %}
{% from '_macros.html' import field_error_messages, error_messages %}

{% block title %}Create new gig{% endblock %}

{% block content %}
  <div class="row">
    <div class="col col-lg-8 offset-2 my-4">
      <h2>Create new gig</h2>
      <form method="POST">
        {{ form.csrf_token }}
        {{ error_messages(form.errors) }}
        <div class="form-group">
          {{ form.title.label }}
          {{ form.title(class="form-control") }}
          {{ field_error_messages(form.title) }}
        </div>
        <div class="form-group">
          {{ form.description.label }}
          {{ form.description(class="form-control") }}
          {{ field_error_messages(form.description) }}
        </div>
        <div class="form-group">
          {{ form.payment.label }}
          {{ form.payment(class="form-control") }}
          {{ field_error_messages(form.payment) }}
        </div>
        <div class="form-group">
          {{ form.location.label }}
          {{ form.location(class="form-control") }}
          {{ field_error_messages(form.location) }}
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-primary form-control") }}
        </div>
      </form>
    </div>
  </div>
{% endblock %}

auth_basic/app/templates/gig/edit_gig.html
{% extends 'base.html' %}
{% from '_macros.html' import field_error_messages, error_messages %}

{% block title %}Update gig {{ gig.title | safe }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col col-lg-8 offset-2 my-4">
      <h2>Update gig -
        <a href="{{ url_for('gig.show', slug=gig.slug) }}">{{ gig.title | safe }}</a>
      </h2>
      <form method="POST">
        {{ form.csrf_token }}
        {{ error_messages(form.errors) }}
        <div class="form-group">
          {{ form.title.label }}
          {{ form.title(class="form-control") }}
          {{ field_error_messages(form.title) }}
        </div>
        <div class="form-group">
          {{ form.description.label }}
          {{ form.description(class="form-control") }}
          {{ field_error_messages(form.description) }}
        </div>
        <div class="form-group">
          {{ form.payment.label }}
          {{ form.payment(class="form-control") }}
          {{ field_error_messages(form.payment) }}
        </div>
        <div class="form-group">
          {{ form.location.label }}
          {{ form.location(class="form-control") }}
          {{ field_error_messages(form.location) }}
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-primary form-control") }}
        </div>
      </form>
    </div>
  </div>
{% endblock %}

auth_basic/app/templates/gig/my_gigs.html
{% extends 'base.html' %}
{% set active_page = 'my_gigs' %}

{% block title %}My gigs{% endblock %}

{% block content %}
  {% if gigs %}
    <h3>
      {% if current_user.is_role(Role.MUSICIAN) %}
        Gigs that you applied to
      {% elif current_user.is_role(Role.EMPLOYER) %}
        Gigs that you have posted
      {% endif %}
    </h3>
    <div class="row my-4">
      {% for gig in gigs %}
        {% include 'gig/_gig.html' %}
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-warning">
      There are no gigs to show.
    </div>
  {% endif %}
{% endblock %}

auth_basic/app/templates/gig/show_gig.html
{% extends 'base.html' %}

{% block title %}{{ gig.title | safe }}{% endblock %}

{% block content %}
  <div class="row my-4">
    <div class="col col-lg-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">
            <img class="gig-img" height="50px"
                 src="{{ url_for('static', filename='images/gig.png') }}"
                 alt="gig.png">
            {{ gig.title | safe }}
            {% if current_user == gig.employer %}
              <div class="button-actions">
                <a href="{{ url_for('gig.edit', slug=gig.slug) }}" class="btn btn-primary">Update</a>
                <form class="delete-form" method="POST" action="{{ url_for('gig.delete', slug=gig.slug) }}">
                  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                  <input type="submit" class="btn btn-danger" value="Delete"
                         onclick="return confirm('Are you sure you want to permanently delete this gig?');">
                </form>
              </div>
            {% endif %}
            {% if current_user.is_role(Role.MUSICIAN) %}
              <div class="button-actions">
                {% if current_user.is_applied_to(gig) %}
                  <button class="btn btn-warning" disabled>Applied...</button>
                {% else %}
                  <form method="POST" action="{{ url_for('gig.apply_to_gig', slug=gig.slug) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <input type="submit" class="btn btn-warning" value="Apply">
                  </form>
                {% endif %}
              </div>
            {% endif %}
          </h3>
          <h4>{{ '$%.2f' | format(gig.payment) }}</h4>
          <p><b>Location:</b> {{ gig.location | safe }}</p>
          <p class="card-text"><em>{{ gig.description | safe }}</em></p>
        </div>
        <div class="card-footer">Posted by:
          <a href="{{ url_for('account.show', username=gig.employer.username) }}">{{ gig.employer.username }}</a>
        </div>

      </div>
      <div class="card my-4">
        <div class="card-header">Musicians applied to this gig</div>
        <div class="card-body">
          {% for musician in musicians %}
            <h3>
              <a href="{{ url_for('account.show', username=musician.username) }}">{{ musician.username }}</a>
            </h3>
            <hr class="card-border">
          {% else %}
            Nothing to show
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}