auth_basic/app/gig/views.py
from functools import wraps

from flask import Blueprint, render_template, flash, redirect, url_for, \
    abort, request
from werkzeug.utils import escape, unescape

from app import db
from app.auth import current_user, login_required, activation_required, role_required
from app.models import Role, Gig
from .forms import CreateGigForm, UpdateGigForm

gig = Blueprint('gig', __name__)


def gig_owner_required(f):
    @wraps(f)
    def _gig_owner_required(*args, **kwargs):
        gig = Gig.query.filter_by(slug=request.view_args.get('slug')).first()
        if not gig or not current_user.is_gig_owner(gig):
            flash('You are not the owner of that gig.', 'danger')
            return redirect(url_for('main.home'))
        return f(*args, **kwargs)

    return _gig_owner_required


@gig.route('/info/<slug>')
@login_required
@activation_required
def show(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    musicians = gig.musicians.all()
    return render_template('gig/show_gig.html', gig=gig, musicians=musicians)


@gig.route('/my_gigs')
@login_required
@activation_required
def my_gigs():
    gigs = None
    if current_user.is_role(Role.EMPLOYER):
        gigs = current_user.gigs.all()
    elif current_user.is_role(Role.MUSICIAN):
        gigs = current_user.applied_gigs.all()

    return render_template('gig/my_gigs.html', gigs=gigs)


@gig.route('/create', methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
def create():
    form = CreateGigForm()
    if form.validate_on_submit():
        gig = Gig(
            title=escape(form.title.data),
            description=escape(form.description.data),
            payment=form.payment.data,
            location=escape(form.location.data),
            employer_id=current_user.id
        )
        db.session.add(gig)
        db.session.commit()
        flash(f'The new gig has been added. "{gig.title}"', 'success')
        return redirect(url_for('gig.show', slug=gig.slug))

    return render_template('gig/create_gig.html', form=form)


@gig.route('/edit/<slug>', methods=["GET", "POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def edit(slug):
    form = UpdateGigForm()
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    if form.validate_on_submit():
        gig.update(
            title=escape(form.title.data),
            description=escape(form.description.data),
            payment=form.payment.data,
            location=escape(form.location.data)
        )
        db.session.add(gig)
        db.session.commit()
        flash('The gig has been updated.', 'success')
        return redirect(url_for('gig.show', slug=gig.slug))

    form.title.data = unescape(gig.title)
    form.description.data = unescape(gig.description)
    form.payment.data = gig.payment
    form.location.data = unescape(gig.location)
    return render_template('gig/edit_gig.html', gig=gig, form=form)


@gig.route('/delete/<slug>', methods=["POST"])
@login_required
@activation_required
@role_required(Role.EMPLOYER)
@gig_owner_required
def delete(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    db.session.delete(gig)
    db.session.commit()
    flash('The gig has been deleted.', 'success')
    return redirect(url_for('gig.my_gigs'))


@gig.route('/apply/<slug>', methods=["POST"])
@login_required
@activation_required
@role_required(Role.MUSICIAN)
def apply_to_gig(slug):
    gig = Gig.query.filter_by(slug=slug).first()
    if not gig:
        abort(404)

    current_user.apply(gig)
    flash(f'You just applied to the gig: "{gig.title}".', 'success')
    return redirect(request.referrer)  # back

auth_basic/app/main.py
from flask import render_template, Blueprint

from app.auth import current_user
from app.models import User, Role, Gig

main = Blueprint('main', __name__)


@main.route('/')
def home():
    gigs = musicians = None
    if current_user.is_role(Role.MUSICIAN):
        gigs = Gig.query.all()
    elif current_user.is_role(Role.EMPLOYER):
        musicians = User.query.filter_by(role_id=Role.MUSICIAN).all()
    return render_template('main/home.html', gigs=gigs, musicians=musicians)

auth_basic/app/templates/main/_authenticated.html
{% if current_user.is_role(Role.EMPLOYER) %}
  {% if not musicians %}
    <div class="alert alert-danger">
      There are no musicians to show.
    </div>
  {% endif %}
  <div class="row my-4">
    <div class="col col-lg-2">
      <a href="{{ url_for('gig.create') }}" class="btn btn-primary">Create new gig</a>
    </div>
    {% if musicians %}
      <div class="col col-lg-10">
        <div class="row">
          {% for musician in musicians %}
            {% include 'account/_musician.html' %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
{% elif current_user.is_role(Role.MUSICIAN) %}
  {% if gigs %}
    <div class="row my-4">
      {% for gig in gigs %}
        {% include 'gig/_gig.html' %}
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-danger">
      There are no gigs to show.
    </div>
  {% endif %}
{% endif %}

auth_basic/app/templates/main/home.html
{% extends 'base.html' %}
{% set active_page = 'home' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if current_user.is_authenticated() %}
    {% if current_user.is_active() %}
      {% include 'main/_authenticated.html' %}
    {% else %}
      <div class="alert alert-warning">
        Please confirm your email.<br>
        <small>Did not get the confirmation email?<br>
          <a href="{{ url_for('auth.send_activation') }}">Send it again</a></small>
      </div>
    {% endif %}
  {% else %}
    <div class="my-4">
      <h1>Bring in the music!</h1>
      <p><a href="{{ url_for('auth.login') }}" class="btn btn-primary">Login</a></p>
    </div>
  {% endif %}
{% endblock %}